version: '3'

volumes:
    duc_database:

services:
  duc-service:
    build: .
    environment:
      # example: everyday at midnight
      - SCHEDULE=0 0 * * *
    # the web server is available on the container's port 80
    expose:
      - 80
    # publish the web server on 8080, for test purposes only - remove this in production and place behind a
    # reverse proxy instead
    ports:
      # expose on 8080
      - 8080:80
    volumes:
      # scan the whole root partition
      - /:/scan/root:ro
      # store the database outside the container
      - duc_database:/database
    networks:
      - proxynet

networks:
  proxynet:
    external: true
